apiVersion: v1
kind: Secret
metadata:
  name: flexify-keys
  namespace: flexify
data:
  FLEXIFY_ENGINE_CLOUD_SECRET_KEY: "<base64 enc storage account key>"
  FLEXIFY_ENGINE_SECRET_KEY: "<base64 enc secret key>"
