apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: flexify-log-claim  
  namespace: flexify 
  labels:
    app.kubernetes.io/component: flexify
    app.kubernetes.io/name: flexify
    app.kubernetes.io/part-of: flexify
    app.kubernetes.io/version: 0.0.1 
spec:  
  accessModes:  
    # - ReadWriteOnce  
    - ReadWriteMany
  # storageClassName: default  
  storageClassName: <storage-class-name>
  resources:  
    requests:  
      storage: 1Gi 