apiVersion: v1  
kind: Service  
metadata:  
  name: flexify-service  
  namespace: flexify 
  labels:
    app.kubernetes.io/component: flexify
    app.kubernetes.io/name: flexify
    app.kubernetes.io/part-of: flexify
    app.kubernetes.io/version: 0.0.1 
    prometheus.io/scrape-prometheus: "true"
  annotations:  
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "app_comp1"
spec:  
  type: ClusterIP  
  sessionAffinity: ClientIP
  ports:  
    - name: https
      port: 443  
      targetPort: 8443
    - name: prom
      port: 8092
      targetPort: 50791
  selector:  
    app.kubernetes.io/component: flexify
    app.kubernetes.io/name: flexify
    app.kubernetes.io/part-of: flexify