{{- if not (lookup "v1" "Secret" .Release.Namespace "flexify-keys") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keys.secretName }} 
  namespace: {{ .Values.namespace }} 
data:
  {{- range $key, $value := .Values.appKeys }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
