apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: {{ .Values.pvc.name }} 
  namespace: {{ .Values.namespace }} 
spec:  
  accessModes:  
    # - ReadWriteOnce  
    - ReadWriteMany
  # storageClassName: default  
  storageClassName: {{ .Values.pvc.storageClassName | default "default" }} 
  resources:  
    requests:  
      storage: {{ .Values.pvc.storage }} 