apiVersion: v1  
kind: Service  
metadata:  
  name: {{ .Chart.Name }}-service  
  namespace: {{ .Values.namespace }}  
  labels:
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.helm.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:  
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.helm.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:  
  type: ClusterIP  
  sessionAffinity: ClientIP
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name | quote }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}  
  selector:  
    {{- with .Values.service.selector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}